#!/bin/sh

#nohup bash -c "time ~/bismark_v0.16.3/bismark --ambiguous --unmapped --sam --pbat  --temp_dir /research/jsporter/Data/output/Human/bismark/Paired-End/PBAT/ -o /research/jsporter/Data/output/Human/bismark/Paired-End/PBAT/ /research/jsporter/Data/genome/GRCh38.p9/bismark/ -1 /research/jsporter/Data/reads/Human/Paired-End/PBAT/SRR2013793_1.500k.fastq -2 /research/jsporter/Data/reads/Human/Paired-End/PBAT/SRR2013793_2.500k.fastq" &> /research/jsporter/Data/output/Human/bismark/Paired-End/PBAT/SRR2013793.500k.bismark.out &

nohup bash -c "time ~/bismark_v0.16.3/bismark --ambiguous --unmapped --sam --pbat  --temp_dir /research/jsporter/Data/output/Human/bismark/Paired-End/PBAT/ -o /research/jsporter/Data/output/Human/bismark/Paired-End/PBAT/ /research/jsporter/Data/genome/GRCh38.p9/bismark/ -1 /research/jsporter/Data/reads/Human/Paired-End/PBAT/DRR084131_2.500k.fastq  -2 /research/jsporter/Data/reads/Human/Paired-End/PBAT/DRR084131_1.500k.fastq" &> /research/jsporter/Data/output/Human/bismark/Paired-End/PBAT/DRR084131.500k.bismark.out &

nohup bash -c "time ~/bismark_v0.16.3/bismark --ambiguous --unmapped --sam --non_directional  --temp_dir /research/jsporter/Data/output/Human/bismark/Single/Nondirectional/ -o /research/jsporter/Data/output/Human/bismark/Single/Nondirectional/ /research/jsporter/Data/genome/GRCh38.p9/bismark/ /research/jsporter/Data/reads/Human/Single/Nondirectional/SRR052371.noN.500k.fastq" &> /research/jsporter/Data/output/Human/bismark/Single/Nondirectional/SRR052371.noN.500k.bismark.out &

#nohup bash -c "time ~/bismark_v0.16.3/bismark --ambiguous --unmapped --sam --non_directional  --temp_dir /research/jsporter/Data/output/Human/bismark/Single/Nondirectional/ -o /research/jsporter/Data/output/Human/bismark/Single/Nondirectional/ /research/jsporter/Data/genome/GRCh38.p9/bismark/ /research/jsporter/Data/reads/Human/Single/Nondirectional/SRR342552.500k.fastq" &> /research/jsporter/Data/output/Human/bismark/Single/Nondirectional/SRR342552.500k.bismark.out &
